services:
    pc_exchange.elementmanager:
        class: PC\ExchangeBundle\Service\ElementManager
        arguments: ["@doctrine.orm.entity_manager"]

    pc_exchange.reviewmanager:
        class: PC\ExchangeBundle\Service\ReviewManager
        arguments: ["@doctrine.orm.entity_manager"]

    pc_exchange.ratinglogic:
        class: PC\ExchangeBundle\Service\RatingLogic
#        arguments: ["@service_id", "plain_value", "%parameter%"]
