<?php

namespace PC\ExchangeBundle\Repository;

/**
 * AdjectiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdjectiveRepository extends \Doctrine\ORM\EntityRepository
{
}
