<?php

namespace PC\ExchangeBundle\Repository;

use \Doctrine\ORM\EntityRepository;
use \Doctrine\ORM\QueryBuilder;

/**
 * ElementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElementRepository extends EntityRepository
{
    public function myFindByCategory($cValue, $tValue) {

        $qb = $this
            ->createQueryBuilder('e')
            ->select('e')
            ->leftJoin('e.categories', 'c')
            ->addSelect('c');

        $qb = $qb
            ->add('where', $qb->expr()->in('c', ':c'))
                ->setParameter('c', $cValue)
            ->andWhere('e.type = :t')
                ->setParameter('t', $tValue);

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function mySearch($value) {

        $qb = $this
            ->createQueryBuilder('e')
            ->leftJoin('e.elementArtists', 'ea')
            ->addSelect('ea')
            ->leftJoin('ea.artist', 'a')
            ->addSelect('a');

        $qb = $qb
            ->add('where', $qb->expr()->orX(
                $qb->expr()->like('e.title', ':val'),
                $qb->expr()->like('a.name', ':val')
                ))
                ->setParameter('val', '%'.$value.'%');

        return $qb
            ->getQuery()
            ->getResult();
    }
}
