<?php

namespace PC\ExchangeBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{

    public function myFindByElement($value) {

        $qb = $this
            ->createQueryBuilder('r')
            ->where('r.element = :eId')
                ->setParameter('eId', $value);

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function myGetProsAndCons($bias, $eltId) {
        //à revoir
        $qb = $this->createQueryBuilder('r')
            ->where('r.element = :eId')
                ->setParameter('eId', $eltId)
            ->leftJoin('r.reviewCriterions', 'rc')
            ->addSelect('rc')
            ->andWhere('rc.bias = :b')
                ->setParameter('b', $bias)
            ->addSelect('COUNT(rc.criterion) AS HIDDEN nb')
            ->groupBy('rc.criterion')
            ->orderBy('nb', 'DESC')
            ->setMaxResults(3)
            ;

        return $qb
            ->getQuery()
            ->getResult();
    }

}
